### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by aaronspring** [mathause/regionmask#118]
covid19 Met Office task forces would like to use this. https://github.com/informatics-lab/covid19-examples-and-docs/pull/10 and ask when there would be a new release

I read somewhere that this last release should still support python2 for the last time

Any more PR you want to see in a new version? @mathause

**Comment by mathause** [comment]
I can make a new release if there is a strong interest for it. I think I would then postpone dropping 2.7 for 0.7.0.

- [ ] #103 is almost ready (awaiting #117 (I am working on this) and docs). 
- [ ] #73 would be next on my list but not a blocker (it would allow to do `ds.weighted(mask_3D * weights).mean(("lat", "lon"))` to calculate the mean of all regions in one go)

**Comment by aaronspring** [comment]
No need to rush
