### ISSUE TITLE
regionmask and dask

### ISSUE THREAD

**Issue by aaronspring** [mathause/regionmask#121]
I naively hoped that `regionmask` could scale when going distributed with `dask` when chunking the input array. But it doesnt. after `regionmask.mask`, data is not lazy anymore.

@mathause do you think regionmask could also scale with dask? or is the current implementation relying somewhere strongly on eager computation/non-dask?

**Comment by mathause** [comment]
regionmask only uses the coordinates from the array so it doesn't really know about the chunking. Which part are you concerned about? Memory footprint or speed? Currently I don't see an easy solution for this. Maybe the array could be chunked after creating the mask? 

Using `xr.map_blocks` would work, but it's much slower (about 40 times for this example):

```python
import regionmask
import xarray as xr

ds = xr.tutorial.open_dataset("air_temperature")
da = ds.air.chunk(dict(lat=10, lon=10))

# need to get rid of coordinates that are not lat and lon
da = da.isel(time=0).drop_vars("time")

def mask_blocks(da):
    
    if sum(da.shape) == 0:
        return da

    return regionmask.defined_regions.srex.mask(da)


mask = xr.map_blocks(msk, da)

mask.plot()
```

**Comment by aaronspring** [comment]
Good comment on the coords. I will think about it. Mostly concerned with speed because on large datasets it takes a while. 
For now I create tmp data.

**Comment by mathause** [comment]
What regions do you use? What are the lat and lon coordinates? I would be interesting to see some timings:

```python
%timeit region.mask(da, method="legacy")
%timeit region.mask(da, method="rasterize")
%timeit region.mask(da, method="shapely")
```

**Comment by aaronspring** [comment]
I am using these data here: https://binder.pangeo.io/v2/gh/aaronspring/covid19-examples-and-docs/AS_pangeo_notebook

**Comment by aaronspring** [comment]
rasterize: `lat` and `lon` must be equally spaced to use`method='rasterize'`

`%time uk_regions_masked = UK_regions.mask(ds, method="legacy")` takes very long


`%time uk_regions_masked = UK_regions.mask(ds, method="shapely")`
CPU times: user 1min 23s, sys: 3.33 s, total: 1min 26s
Wall time: 1min 26s

**Comment by mathause** [comment]
Thanks for the binder notebook. The obvious way would of course be to crop `ds` to GB. However, it's actually an interesting case I thought will come sooner or later ;) but I haven't got around to implement it.

Could you try:
```python
%time UK_regions.mask(ds.lon - 180, ds.lat)
```
Now it internally uses `method="rasterize"` (#122) - it's impressive how much faster rasterio (gdal) is. But this method requires that your grid is equally spaced. Your regions cross the prime meridian but `ds.lat` goes from 0 to 360. Therefore, the latitude is wrapped around and your grid is no longer equally spaced.

```python
print(regionmask.core.mask.equally_spaced(ds.lon, ds.lat))
lon_wrapped = regionmask.core.mask._wrapAngle(ds.lon)
print(regionmask.core.mask.equally_spaced(lon_wrapped, ds.lat))
```

What now needs to be done (in regionmask) is to split `lon_wrapped` into two parts and mask both parts individually and then stick them together again.

**Comment by aaronspring** [comment]
I will try later. This might speed up masking but not because it uses distributed scheduling with dask. 

dask could maybe parallelise the looping over regions when masking. But usually with dask coords are loaded into memory.

**Comment by aaronspring** [comment]
Croping UK is a bit tricky for the 360/0 lat bound. Looking into a neat fix for that in general.

**Comment by aaronspring** [comment]
way faster.
```
%time uk_regions_masked = UK_regions.mask(ds.lon - 180, ds.lat)
CPU times: user 64.5 ms, sys: 93.8 ms, total: 158 ms
Wall time: 156 ms
```

**Comment by aaronspring** [comment]
Summary. Using method rasterize massively speeds up .mask. The groupby Operation should scale with dask natively.

**Comment by mathause** [comment]
Thanks, I opened a new issue for this.

**Comment by mathause** [comment]
#132 should solve this problem. I also did some tests with dask - I manage to saturate my 8 cores, but in the end it's only about twice as fast, so there must be quite some overhead. (Which is not to say that someone with mote dask experience might get more performance out of this, not sure if I did it right.)
