### ISSUE TITLE
Improve error message when numbers aren't numeric

### ISSUE THREAD

**Issue by zbruick** [mathause/regionmask#130]
Really love this package - thanks for the work!

One error I found when creating masks was that if `numbers` was provided a list of strings, regions are created, but the mask creation fails with the following error: `TypeError: cannot perform reduce with flexible type`. Easy solution is to force the numbers list to be numeric, but this is not an obvious fix. An improved error message would be helpful in quickly solving this problem.

**Comment by mathause** [comment]
Yes, good point - this error message is not helpful at all. I'll fix that.
