### ISSUE TITLE
More control for colours in plot routines

### ISSUE THREAD

**Issue by rjp23** [mathause/regionmask#140]
It'd be great if there was more control built in for colours in the plot routines. For example, the ocean colour is set as a default, the land colour can't be changed (and if you manually add your own Natural Earth land colour it covers the regions).

I think just passing some extra keywords in for the various colour options would be quite straightfoward and add a lot of flexability.

**Comment by mathause** [comment]
Yes it is certainly a good idea to expose the color as a `kwarg`.

> it covers the regions

Do you mean if a mask is plotted? Yes indeed this seems to require to set the zorder explicitly (also for the ocean). This should be fixed.

Would you find it useful if a `add_land` keyword was added so the land could be colored as well?

On a related note: I thought about not coloring the ocean by default (#58). Not sure if that warrants a deprecation note or if that would only be noise.

**Comment by rjp23** [comment]
Yep, it's a zorder issue I believe.

add_land would be useful as would exposing all the keywords. Just a bit more flexibility.
