### ISSUE TITLE
No mask_geopandas attribute

### ISSUE THREAD

**Issue by hectorpatino** [mathause/regionmask#150]
### System
Windows 10 Home Single Language 64 bits

### conda 
version 4.8.2

I just clone the repository and try to reproduce the geopandas notebook locate at docs/notebook folder, but cell 6 raises and excepcion of Attribute Error
`AttributeError       Traceback (most recent call last)
<ipython-input-6-61a3e9f7cb7a> in <module>
      2 lat = np.arange(-90, 90)
      3 
----> 4 mask = regionmask.mask_geopandas(continents, lon, lat)

AttributeError: module 'regionmask' has no attribute 'mask_geopandas'`

i was reading the docs, and the api, but wasn't able to make it work. followed the instructions on [installation](https://regionmask.readthedocs.io/en/stable/installation.html). 

I executed the other notebooks and they are ok.

**Comment by mathause** [comment]
Thanks for your interest in regionmask. `mask_geopandas` is only available in the upcoming version that is not yet released. If you want to use it you will have to install it directly from git:

```
conda remove regionmask
pip install git+https://github.com/mathause/regionmask.git
```

**Comment by hectorpatino** [comment]
Thank you!
