### ISSUE TITLE
Subsetting for AR6

### ISSUE THREAD

**Issue by mada0007** [mathause/regionmask#191]
WAF =dset_JJA.where(mask == regionmask.defined_regions.srex.map_keys('WAF')).mean(dim=['lon','lat']) 
 I cant do this for AR5 regions. How can I repeat same for AR6 regions?

**Comment by mathause** [comment]
I don't understand what the question is. Can you add a reproducible example.

**Comment by mada0007** [comment]
Thanks all sorted out now.
