### ISSUE TITLE
mask_3d computes unneeded regions

### ISSUE THREAD

**Issue by atsfmc** [mathause/regionmask#209]
I am working with some shapely defined regions. I want to create a mask over some non-uniformly distributed data points, say weather data from weather stations.

So say I have N data points. When I mask on this data it looks I get information for N^2 data points, the Cartesian product of all latitudes and longitudes, but all I really want are the values on the diagonal of the lat, lon matrix. Only N data points.

Is there some way to only compute these requested data points?

**Comment by mathause** [comment]
regionmask is written with gridded data in mind - so when you pass a vector of data it assumes that these are the coordinates of a grid - and it will return you the grid:

```python
In [5]: regionmask.defined_regions.ar6.land.mask([1, 2], [1, 2])
Out[5]: 
<xarray.DataArray 'region' (lat: 2, lon: 2)>
array([[nan, nan],
       [21., 21.]])
Coordinates:
  * lat      (lat) int64 1 2
  * lon      (lon) int64 1 2
```

However, there is a way around this - when you pass a 2D field of coordinates, it will check if each point is contained in a polygon:

```python
In [6]: regionmask.defined_regions.ar6.land.mask([[1, 2]], [[1, 2]])
Out[6]: 
<xarray.DataArray (lon_idx: 1, lat_idx: 2)>
array([[nan, 21.]])
Coordinates:
  * lon_idx  (lon_idx) int64 0
  * lat_idx  (lat_idx) int64 0 1
    lat      (lon_idx, lat_idx) int64 1 2
    lon      (lon_idx, lat_idx) int64 1 2
```

Internally this will call the following function using `shapely.vectorized.contains`: 

https://github.com/mathause/regionmask/blob/1dc7895a00a15d26ab37e65f17acc7037608d162/regionmask/core/mask.py#L363

**Comment by atsfmc** [comment]
Thanks. This should be exactly what I was looking for.
