### ISSUE TITLE
Speedup of mask method

### ISSUE THREAD

**Issue by jhamman** [mathause/regionmask#24]
I've been trying out regionmask and have hit a few performance bottlenecks. I should say, other than these bottlenecks, I really like the functionality here.

I compared the time it takes to rasterize a the [USGS HUC2](https://water.usgs.gov/GIS/huc.html) river basin polygons to the 1/8th deg grid resolution. I'm finding that the following implementation is roughly 100x faster (2 seconds vs 3 minutes). I suspect I'm using `regionmask` on a dataset / shapefile collection that is larger than it was designed for.  It is possible that regionmask is doing something that my code is not but I though I'd post my approach here and see if it would be useful to this package.

```Python
from affine import Affine
from rasterio import features


def transform_from_latlon(lat, lon):
    '''perform an affine tranformation to the latitude/longitude coordinates'''
    lat = np.asarray(lat)
    lon = np.asarray(lon)
    trans = Affine.translation(lon[0], lat[0])
    scale = Affine.scale(lon[1] - lon[0], lat[1] - lat[0])
    return trans * scale


def rasterize(shapes, coords, fill=np.nan, **kwargs):
    """Rasterize a list of (geometry, fill_value) tuples onto the given
    xarray coordinates. This only works for 1d latitude and longitude
    arrays.
    """
    transform = transform_from_latlon(coords['lat'], coords['lon'])
    out_shape = (len(coords['lat']), len(coords['lon']))
    raster = features.rasterize(shapes, out_shape=out_shape,
                                fill=fill, transform=transform,
                                dtype=np.float, **kwargs)
    return xr.DataArray(raster, coords=coords, dims=('lat', 'lon'), name='region')
```

with a call that looks like:

```Python
# hucs[2] is a geopandas.GeoDataFrame
masks = rasterize(zip(hucs[2].geometry, hucs[2].index),
                  coords={'lon': subset.coords['lon'],
                          'lat': subset.coords['lat']})
```

**Comment by mathause** [comment]
Thanks, this looks promising. Still need to test some edge-cases (e.g. point on line). The coordinates need to be 1D and the spacing must be equal, right?

**Comment by jhamman** [comment]
@mathause - yes, I'm sure there are some edge cases that this doesn't cover. Given its performance though, it may be worth adding as a fast-track for regular grids.

**Comment by byersiiasa** [comment]
alerting @gidden who I think will like this package.
Aside from speed issues - @gidden may be able to give pointers on different rasterization methods

**Comment by mathause** [comment]
Finally implemented this! It only took two years ;) Thanks.
