### ISSUE TITLE
How do I mask xarray DataArray using custom shapely file?

### ISSUE THREAD

**Issue by tommylees112** [mathause/regionmask#28]
I have an ethiopia mask and a region of Ethiopia mask. They are stored as GeoPandas GeoDataFrames and the geometry is a shapely polygon.

```python
import regionmask
numbers = [0, 1]
names = ['ethiopia', 'awash']
abbrevs = ['eth', 'awa']

# extract the shapely geometry from the Geopandas geodataframe
ethiopia_poly = ethiopia.geometry.values[0]
awash_poly = awash.geometry.values[0]

# create a new 
ethiopia_mask_poly = regionmask.Regions_cls('Eth_mask', numbers, names, abbrevs, [ethiopia_poly,awash_poly])
ethiopia_mask = ethiopia_mask_poly[0]
```
I have an xarray dataset of vegetation health (NDVI). 

It looks like this:
![screenshot 2018-07-06 20 28 06](https://user-images.githubusercontent.com/21049064/42396797-24a65b54-815b-11e8-8310-235b3bbabb03.png)

The shapeley file when plotted on top looks like this:
![screenshot 2018-07-06 20 30 54](https://user-images.githubusercontent.com/21049064/42396871-7febc0f8-815b-11e8-908c-43bf7e40ee1f.png)

How do i use regionmask to mask this region from the xarray?

**Comment by mathause** [comment]
This should be possible by doing 

    mask = ethiopia_mask_poly.mask(NDVI)
    NDVI.where(mask == 1)

but if this does not work, I would need to see the datasets to further investigate.
