### ISSUE TITLE
Including boundary lines and details from Natural earth

### ISSUE THREAD

**Issue by laurensstoop** [mathause/regionmask#29]
Hi Mathause,

I was wondering if you would consider extending regionmask to allow it to also select details and boundary lines  (naval 200 mile zone) as current GCM's are now able to resolve the naval boundary region. 

kind regards,
Laurens

**Comment by mathause** [comment]
Hej Laureens,

can you explain what you mean with details?
Do you want to select all points along a line?

As for the naval 200 mile zone - if there is a freely available dataset I am happy to include it.

**Comment by laurensstoop** [comment]
Hi Mathause,

The naval 200 miles zone is not availabe at Natural Earth due  to licensing issues. But you can find it available for free on http://www.marineregions.org/sources.php#unioneezcountry.

The details is a subgroup of the Natural Earth country data. I misread the information it would give and I don't think anymore it would provide additional information/use to this package.

**Comment by laurensstoop** [comment]
Hi Mathause,

Thank you very much for the example!
