### ISSUE TITLE
Indexing error when mask is only one gridcell in x and/or y direction

### ISSUE THREAD

**Issue by laurensstoop** [mathause/regionmask#30]
` File "/home/stoop/anaconda3/lib/python3.6/site-packages/salem/sio.py", line 280, in _lonlat_grid_from_dataset
    dy = lat[1]-lat[0]
[...]
IndexError: index 1 is out of bounds for axis 0 with size 0`

This error is caused by the fact that the mask is only one gridcell long in a certain direction. 
Maybe a general dy or dx definition could be made?

I am trying to select narrow regions, based on the Eurostat NUTS levels, from my data for climatology analysis.

**Comment by mathause** [comment]
I see the error message results from salem - are you sure this is a regionmask problem? Can you add reproducible example?

The mask should have the same (lat/ lon) shape as the input dataset, so unless your original dataset has size 0 x n, this probably happens at a later stage. What can easily happen is that one of your regions has 0 selected gridcells - did you plot the resulting map?

Do you select data based on a mask (e.g. `ds.flatten()[mask.flatten() == 1]`)?

**Comment by laurensstoop** [comment]
Double checking made that if I chose the margin (a function of salem) to high that the code failed. 

Sorry for the inconvenience, but I couldn't find a fault yesterday.
