### ISSUE TITLE
add from_* tools

### ISSUE THREAD

**Issue by mathause** [mathause/regionmask#42]
``` python
from_shapefile
from_geopandas
from_dict_or_list
from_natural_earth
```

anything else?

**Comment by aaronspring** [comment]
at which level would you implement these? regionmask.from_shapefile?

and what would be the difference for from_shapefile and from_geopandas for you? how else would you open a shapefile?

**Comment by mathause** [comment]
I thought `from_shapefile` would take the name of a shapefile and internally call `from_geopandas`, similarly for `from_natural_earth`. I think `from_dict_or_list` is no longer necessary with 0.5.0.

Thus, `from_geopandas` is the most important one, and I wouldn't bother about the others.

I think in terms of discoverability it is better to have `regionmask.from_geopandas` than `regionmask.Regions.from_geopandas`.

**Comment by aaronspring** [comment]
ok. #96 introduces `regionmask.from_geopandas`

**Comment by mathause** [comment]
- [ ] `from_shapefile` -> use `from_geopandas`
- [x] `from_geopandas` -> implemented
- [x] `from_dict_or_list` -> should work with `Regions(...)`
- [ ] `from_natural_earth` -> use `from_geopandas`

so I close this
