### ISSUE TITLE
Mathaus

### ISSUE THREAD

**Issue by mada0007** [mathause/regionmask#85]
Hi Mathaus, I am relatively new to python, can you point me to how can I can use the AR6 regions?

Cheers,

**Comment by mathause** [comment]
Dear Mada,

as it is a feature branch you have to install it with pip:

``` bash
pip install git+https://github.com/mathause/regionmask.git@feature/ar6_regions
```
for the usage I have to refer you to the documentation: https://regionmask.readthedocs.io/en/stable/ Check out the tutorials.
