### ISSUE TITLE
Add new regions from remote url locations via yaml

### ISSUE THREAD

**Issue by aaronspring** [mathause/regionmask#93]
https://www.marineregions.org/downloads.php

Implement with caching of download. See other issue.

**Comment by aaronspring** [comment]
I work on a solution in a notebook that downloads a few other shapefiles from that site and others. have to make it look nicer. PR will follow soon.

**Comment by aaronspring** [comment]
Copied from #96 

I think the main discussion point here for this PR should be the downloading approach:

from repo (+: sources wont disappear; -: licencing, more to maintain)
from url (+: easily customizable; -: source can disappear)


I would like to implement this second approach. The first approach can also be implemented. The two approach don’t exclude each other.  

Other users can easily prototype regions with new shapefiles from somewhere on the internet. Contributing these to regionmask then wouldn’t even require a new installation. And a contribution to the repo would then just require a new entry in the yaml file. Testable with ci. 

Thoughts @mathause ?

**Comment by mathause** [comment]
I think both of them would be nice additions and don't contradict each other - optimally they should be implemented similarly.


Looking at this from a development/ maintainability perspective 

from repo should be relatively straightforward (vendor the [code](https://github.com/pydata/xarray/blob/master/xarray/tutorial.py)+[tests](https://github.com/pydata/xarray/blob/master/xarray/tests/test_tutorial.py) from xarray with minimal changes).

from url is potentially quite a bit harder to get right - your closed PR is looks quite thorough but would need a ton of tests to be sure all parts work as intended. Maybe there is some inspiration to be found from [cartopy](https://github.com/SciTools/cartopy/blob/master/lib/cartopy/io/__init__.py#L86) but I haven't checked that thoroughly.

I also wonder what the best way would be to define regions - yaml or maybe a subclassing a `RemoteRegions` class? The second has IMHO the advantage that it could contain a method `prepare` which would modify the geodataframe if necessary. E.g. in #61 I want to concatenate some regions, and in #91 some regions had to be renamed.

---

Already with `from_geopandas` and `mask_geopandas` (#103) the package is much easier to extend than before. Especially as geopandas can directly read zip files and urls (I didn't know that).

**Comment by aaronspring** [comment]
the new https://github.com/intake/intake_geopandas now can cache shapefiles when the most recent geopandas is installed. based on that I was thinking of `intake_regionmask` although that would be quite specific. Idea: build `regionmask.region` from yaml, see #138

**Comment by mathause** [comment]
Thanks. I personally don't use intake. So I am not sure what this would entail.

Maybe it could help to make it easier to work with GeoDataFrames in regionmask: (1) use a GeoDataFrame as native backend for regionmask (#49) and (2) relax some of the requirements for names and abbreviations in regionmask.

**Comment by aaronspring** [comment]
working example: https://gist.github.com/aaronspring/ddf15d7bf9908c1f34b19320bd678fdd

**Comment by mathause** [comment]
Thanks, that's pretty cool!

**Comment by mathause** [comment]
Do you have a documentation I can link to somewhere? Else it would be cool to add the example to the regionmask docu.
